### ISSUE TITLE
Error installing on MacOS

### ISSUE THREAD

**Issue by hecoding** [t-makaro/nb_pdf_template#1]
Hi, I wanted to say thank you for your work. It's been useful to me so far.

I was trying to install it through pip but ran into an error when issuing the second command `python -m nb_pdf_template.install.py`.
I saw it was only tested on Windows. I'm using MacOS High Sierra with a fresh Anaconda installation.

Here is the output, in case it is helpful.
```
$ pip install nb_pdf_template
Collecting nb_pdf_template
  Downloading nb_pdf_template-0.9.2.tar.gz
Building wheels for collected packages: nb-pdf-template
  Running setup.py bdist_wheel for nb-pdf-template ... done
  Stored in directory: /Users/<user>/Library/Caches/pip/wheels/b6/56/2e/0542bcc86c3a42f83de0d54fffd7aa8ec64412a78810cde20e
Successfully built nb-pdf-template
Installing collected packages: nb-pdf-template
Successfully installed nb-pdf-template-0.9.2
```
```
$ python -m nb_pdf_template.install.py
Success
/Users/<user>/anaconda3/bin/python: Error while finding module specification for 'nb_pdf_template.install.py' (AttributeError: module 'nb_pdf_template.install' has no attribute '__path__')
```

However the notebook conversion works as expected:
```
$ jupyter nbconvert --to pdf ass8.ipynb --template jupyter.tplx
[NbConvertApp] Converting notebook ass8.ipynb to pdf
[NbConvertApp] Support files will be in ass8_files/
[NbConvertApp] Making directory ass8_files
[NbConvertApp] Making directory ass8_files
[NbConvertApp] Writing 31241 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', 'notebook.tex']
[NbConvertApp] Running bibtex 1 time: ['bibtex', 'notebook']
[NbConvertApp] WARNING | bibtex had problems, most likely because there were no citations
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 58244 bytes to ass8.pdf
```

Cheers!

**Comment by t-makaro** [comment]
That error that occurs while running ```python -m nb_pdf_template.install.py``` occurs on windows too, but the error occurs after the last line in the script (```print("Success")```), so it still works. I'm not entirely sure why it errors. If you navigate directly to the directory of the install script and run ```python install.py``` then no error is given. At some point, I hope to fix that, but for now it still works.

Thank you for letting me know that it works on MacOS.

**Comment by hecoding** [comment]
Ah, ok. Well now you have some feedback from other platforms 😃 

You're welcome! Thank you.
Shall I close the issue then?

**Comment by t-makaro** [comment]
I found the issue. It turns out that the command should be:
```python -m nb_pdf_template.install```
I've updated the readme accordingly.

**Comment by hecoding** [comment]
Great! Thanks for your time.

PD: the new command works on my machine too.
