### ISSUE TITLE
Wrap print output

### ISSUE THREAD

**Issue by lamping7** [t-makaro/nb_pdf_template#14]
As discussed in #13 a print statement output doesn't wrap. In my case some of these are purely introspection to help debug and see what is going on. So, sometimes I'm printing dictionaries or lists that can be too long. Anyways, you hinted at having a solution for this. Thanks for the work you've done here. You've somehow managed to fix the most annoying part about jupyter notebooks for me.

**Comment by t-makaro** [comment]
As a temporary work around:

```
import textwrap
def wrapped_print(obj, width=94):
    test=str(obj)
    split_text = text.split('\n')
    wrp = map(lambda x: textwrap.wrap(x,width), split_text)
    wrpd = map('\n'.join, wrp)
    print('\n'.join(wrpd))
```

This was actually modified from the filter that nbconvert uses to wrap text. I'll try to add the filter to the appropriate place and make a new release soon.

**Comment by t-makaro** [comment]
Just as a warning. I might refactor the way that the minted templates are used in the future. #15

**Comment by t-makaro** [comment]
Released in 2.0.2

**Comment by lamping7** [comment]
Awesome! Thanks. Just an FYI, v2.0.2 doesn't include the minted fix (https://github.com/t-makaro/nb_pdf_template/commit/55ef9c22bda7adabaa28ae209043ba5b04bc9434) but that's probably OK since you're working on other changes.

**Comment by t-makaro** [comment]
I must have forgot to update the distribution before uploading. I just uploaded 2.0.3.
